# Generated by Django 4.2.20 on 2025-04-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('country', models.CharField(blank=True, default='ایران', max_length=20, null=True, verbose_name='کشور')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کاربر خریدار',
                'verbose_name_plural': 'کاربران خریدار',
            },
        ),
        migrations.CreateModel(
            name='StoredLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='آدرس')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_locations', to='user_module.userprofile')),
            ],
            options={
                'verbose_name': 'مکان ذخیره شده',
                'verbose_name_plural': 'مکان ها ذخیره شده',
            },
        ),
    ]
