# Generated by Django 4.2.20 on 2025-04-05 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import product_module.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان زیر دسته بندی')),
                ('url_title', models.CharField(default=product_module.models.generate_random_string, max_length=300, verbose_name='عنوان زیر دسته بندی در url')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=350, verbose_name='عنوان در url')),
                ('ordering_number', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('parent_category', models.CharField(default='cafe_menu', max_length=50, verbose_name='دسته بندی والد محصول کافه')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('is_verified', models.BooleanField(verbose_name='تأیید  / مردود')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول کافه',
                'verbose_name_plural': 'دسته بندی محصولات کافه',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان ویژگی')),
                ('url_title', models.CharField(max_length=255, null=True, verbose_name='عنوان انگلیسی ویژگی')),
                ('feature_type', models.CharField(choices=[('cafe', 'منوی کافه'), ('shop', 'محصول فروشگاهی')], max_length=10, verbose_name='نوع ویژگی کافه/فروشگاهی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=350, verbose_name='عنوان در url')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصول',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('en_name', models.CharField(max_length=300, verbose_name='نام انگیسی محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=350, verbose_name='عنوان در url')),
                ('product_type', models.CharField(choices=[('cafe', 'منوی کافه'), ('shop', 'محصول فروشگاهی')], max_length=10, verbose_name='نوع محصول کافه/فروشگاهی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات اصلی')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('is_special', models.BooleanField(default=False, verbose_name='اسپشیالیتی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده؟')),
                ('show_in_shop', models.BooleanField(default=True, verbose_name='نمایش در پنل فروشگاه / عدم نمایش')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده / نشده')),
                ('is_wholesale', models.BooleanField(default=False, verbose_name='فروش عمده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام برند')),
                ('en_title', models.CharField(default=product_module.models.generate_random_string, max_length=300, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=350, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='عنوان پیشنهاد ویژه')),
                ('bundle_price', models.IntegerField(verbose_name='قیمت بسته')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده / نشده')),
            ],
            options={
                'verbose_name': 'باندل محصول',
                'verbose_name_plural': 'باندل محصولات',
            },
        ),
        migrations.CreateModel(
            name='ShopProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان زیر دسته بندی')),
                ('url_title', models.CharField(default=product_module.models.generate_random_string, max_length=300, verbose_name='عنوان زیر دسته بندی در url')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=350, verbose_name='عنوان در url')),
                ('ordering_number', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image', models.ImageField(blank=True, default='default_images/product_category/product_category.jpg', null=True, upload_to='images/shop_product_category', verbose_name='تصویر دسته بندی')),
                ('parent_category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('coffee', 'دانه/پودر'), ('machines', 'دستگاه ها'), ('capsules', 'کپسول ها'), ('brewing_tools', 'تجهیزات دم آوری'), ('barista_tools', 'تجهیزات باریستا'), ('drip_bags', 'فوری/کیسه ای'), ('grinders', 'آسیاب ها'), ('coffee_makers', 'قهوه ساز ها')], max_length=100, null=True, verbose_name='دسته بندی والد محصول')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول فروشگاه',
                'verbose_name_plural': 'دسته بندی محصولات فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ProductMediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('product', 'تصویر محصول'), ('cafeproductcategory', 'تصویر دسته بندی کافه')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=product_module.models.product_media_files_upload_path, verbose_name='فایل')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='کپشن فایل')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_media_files', to='shop_module.shop')),
            ],
            options={
                'verbose_name': 'فایل مربوط به محصول کافه/فروشگاه',
                'verbose_name_plural': 'فایلهای مربوط به محصولات کافه/فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(max_length=255, null=True, verbose_name='مقدار ویژگی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product_module.feature', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی محصول',
                'verbose_name_plural': 'مقادیر ویژگی های محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='product_module.productbundle', verbose_name='باندل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مورد باندل محصول',
                'verbose_name_plural': 'موارد باندل محصولات',
            },
        ),
        migrations.AddField(
            model_name='productbundle',
            name='products',
            field=models.ManyToManyField(related_name='bundles', through='product_module.ProductBundleItem', to='product_module.product', verbose_name='محصولات بسته'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='shop_module.shop', verbose_name='کافه/فروشگاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.productbrand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='cafe_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_module.cafeproductcategory', verbose_name='دسته\u200cبندی محصولات کافه'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='product_image', to='product_module.productmediafiles', verbose_name='تصویر محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_module.shop', verbose_name='کافه/فروشگاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_module.shopproductcategory', verbose_name='دسته\u200cبندی محصولات فروشگاه'),
        ),
        migrations.AddField(
            model_name='cafeproductcategory',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_product_category_image', to='product_module.productmediafiles', verbose_name='تصویر دسته بندی محصول کافه'),
        ),
        migrations.AddField(
            model_name='cafeproductcategory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category_shop', to='shop_module.shop', verbose_name='کافه'),
        ),
    ]
