# Generated by Django 4.2.20 on 2025-04-07 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productmediafiles_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmediafiles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
