# Generated by Django 4.2.20 on 2025-04-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_productmediafiles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='en_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام انگیسی محصول'),
        ),
    ]
