# Generated by Django 4.2.20 on 2025-04-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_product_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmediafiles',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='تصویر پیش\u200cفرض'),
        ),
    ]
