# Generated by Django 4.2.20 on 2025-04-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productmediafiles_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmediafiles',
            old_name='is_default',
            new_name='is_global',
        ),
    ]
