# Generated by Django 4.2.20 on 2025-04-08 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0004_alter_shopmediafiles_id'),
        ('product_module', '0007_rename_is_default_productmediafiles_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmediafiles',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_media_files', to='shop_module.shop'),
        ),
    ]
