# Generated by Django 4.2.20 on 2025-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_productmediafiles_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmediafiles',
            name='optimized',
            field=models.BooleanField(default=False),
        ),
    ]
