# Generated by Django 4.2.20 on 2025-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_productmediafiles_optimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
