# Generated by Django 4.2.20 on 2025-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_product_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_additive',
            field=models.BooleanField(default=False, verbose_name='افزودنی'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت با تخفیف'),
        ),
    ]
