# Generated by Django 4.2.20 on 2025-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_feature_is_additive_productfeature_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmediafiles',
            name='media_category',
            field=models.CharField(blank=True, choices=[('product', 'انواع قهوه'), ('cold_drinks', 'انواع نوشیدنی خنک')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productmediafiles',
            name='media_type',
            field=models.CharField(choices=[('product', 'تصویر محصول'), ('cafeproductcategory', 'تصویر دسته بندی کافه')], max_length=30),
        ),
    ]
