# Generated by Django 4.2.20 on 2025-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_productmediafiles_media_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordering_number',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productmediafiles',
            name='media_category',
            field=models.CharField(blank=True, choices=[('hot_drinks', 'انواع نوشیدنی گرم'), ('cold_drinks', 'انواع نوشیدنی خنک'), ('cakes', 'انواع کیک و دسر'), ('shakes', 'انواع شیک')], max_length=30, null=True),
        ),
    ]
