# Generated by Django 4.2.20 on 2025-04-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeproductcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
