# Generated by Django 4.2.20 on 2025-04-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_alter_cafeproductcategory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeproductcategory',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید  / مردود'),
        ),
    ]
