# Generated by Django 4.2.20 on 2025-04-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_cafeproductcategory_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeproductcategory',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_product_category_image', to='product_module.productmediafiles', verbose_name='تصویر دسته بندی محصول کافه'),
        ),
    ]
