# Generated by Django 4.2.20 on 2025-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_alter_cafeproductcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeproductcategory',
            name='parent_category',
            field=models.CharField(choices=[('cafe_menu', 'منوی کافه'), ('breakfast', 'منوی صبحانه'), ('foods', 'منوی غذا'), ('deserts', 'منوی پیش غذا')], default='cafe_menu', max_length=50, verbose_name='دسته بندی والد محصول کافه'),
        ),
    ]
