# Generated by Django 4.2.20 on 2025-04-20 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_alter_cafeproductcategory_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeproductcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafeproductcategory',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی'),
        ),
    ]
