# Generated by Django 4.2.20 on 2025-04-20 06:29

from django.db import migrations, models
import product_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0022_cafeproductcategory_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeproductcategory',
            name='url_title',
            field=models.CharField(blank=True, default=product_module.models.generate_random_string, max_length=300, null=True, verbose_name='عنوان زیر دسته بندی در url'),
        ),
    ]
