# Generated by Django 4.2.20 on 2025-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_alter_cafeproductcategory_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeproductcategory',
            name='url_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان زیر دسته بندی در url'),
        ),
    ]
