# Generated by Django 4.2.20 on 2025-04-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0024_alter_cafeproductcategory_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmediafiles',
            name='media_category',
            field=models.CharField(blank=True, choices=[('hot_drinks', 'انواع نوشیدنی گرم'), ('cold_drinks', 'انواع نوشیدنی خنک'), ('cakes', 'انواع کیک و دسر'), ('shakes', 'انواع شیک'), ('beans', 'دانه قهوه'), ('powder', 'پودر قهوه')], max_length=30, null=True),
        ),
    ]
