# Generated by Django 4.2.20 on 2025-04-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_module', '0001_initial'),
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('internal', 'سفارش داخلی'), ('external', 'سفارش خارجی')], default='internal', max_length=20, verbose_name='نوع سفارش داخلی/خارجی')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مشتری')),
                ('table_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره میز')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده / نشده')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_temp_orders', to='shop_module.shop', verbose_name='کافه/فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد سفارش',
                'verbose_name_plural': 'سبدهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی تکی محصول')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order_module.order', verbose_name='جزئیات سفارش موقت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_temp_order_products', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش',
                'verbose_name_plural': 'لیست جزئیات سفارش',
            },
        ),
    ]
