# Generated by Django 4.2.20 on 2025-04-05 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد اعتبارسنجی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
            ],
            options={
                'verbose_name': 'کد اعتبارسنجی',
                'verbose_name_plural': 'کدهای اعتبارسنجی',
            },
        ),
    ]
