# Generated by Django 4.2.20 on 2025-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='طراحی سایت')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='دامنه سایت')),
                ('office_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس دفتر شرکت')),
                ('office_phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن دفتر شرکت')),
                ('backup_phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن پشتیبانی')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس دفتر شرکت')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل شرکت')),
                ('copy_right_text', models.TextField(verbose_name='متن کپی رایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('founder', models.CharField(max_length=200, null=True, verbose_name='بنیانگذار')),
                ('site_logo', models.ImageField(upload_to='images/site_setting/logo', verbose_name='لوگو سایت')),
                ('instagram_link', models.URLField(null=True, verbose_name='لینک اینستاگرام')),
                ('linkedin_link', models.URLField(null=True, verbose_name='لینک لینکدین')),
                ('facebook_link', models.URLField(null=True, verbose_name='لینک فیسبوک')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
