# Generated by Django 4.2.20 on 2025-04-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='E_namad_code',
            field=models.TextField(blank=True, null=True, verbose_name='کد اینماد'),
        ),
    ]
