# Generated by Django 4.2.20 on 2025-04-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_sitesetting_e_namad_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='old_token_deletion',
            field=models.PositiveIntegerField(default=15, verbose_name='اعتبار توکن های اعضاء'),
        ),
    ]
