"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from datetime import timedelta

# from utils_module.utils import custom_exception_handler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-u5a+mhl")

# Environment-specific settings
DJANGO_ENV = config("DJANGO_ENV", default="development")  # 'production' for live server

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)
# DEBUG = True

# ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=list, default=["http://localhost:3000"])
# ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv(), default=["127.0.0.1", "localhost"])
# ALLOWED_HOSTS = ["127.0.0.1", "localhost", "fee-coffee.com", "www.fee-coffee.com", "feecoffee-front.liara.run",
#                  "www.feecoffee-front.liara.run"]

if DJANGO_ENV == 'development':
    ALLOWED_HOSTS = config(
        "ALLOWED_HOSTS_DEV",
        cast=Csv(),
        default="fee-coffee.com,www.fee-coffee.com"
    )
else:
    ALLOWED_HOSTS = config(
        "ALLOWED_HOSTS_PRO",
        cast=Csv(),
        default="fee-coffee.com,www.fee-coffee.com"
    )

if not ALLOWED_HOSTS:
    raise ValueError("ALLOWED_HOSTS environment variable must be set.")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # internals
    'accounts_module',
    'home_module',
    'article_module',
    'shop_module',
    'product_module',
    'site_module',
    'auth_sms_module',
    'user_module',
    'cafe_market_module',
    'shop_market_module',
    'utils_module',
    'media_collection_module',
    'order_module',
    # externals
    'corsheaders',
    'rest_framework',
    # 'rest_framework_simplejwt',
    'rest_framework.authtoken',
    # 'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'django_filters',
]
if DEBUG:
    INSTALLED_APPS += [
        'django_extensions',  # Added only when DEBUG is True
        # any other development-specific apps
    ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # اضافه کردن در ابتدای لیست
    'django.middleware.security.SecurityMiddleware',
    # Insert our custom middleware for non-production environments.
    # This middleware will add X-Robots-Tag header to responses.
    'core.middleware.NoIndexMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # "core.middleware.JWTBlacklistMiddleware",  # Add this line
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Remove NoIndexMiddleware in production if needed by conditionally modifying the chain
if DJANGO_ENV == "production":
    MIDDLEWARE = [mw for mw in MIDDLEWARE if mw != 'core.middleware.NoIndexMiddleware']

if DEBUG:
    INSTALLED_APPS += ['silk', ]
    MIDDLEWARE = ['silk.middleware.SilkyMiddleware'] + MIDDLEWARE

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,  # Wait up to 20 seconds
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config("MYSQL_DB_NAME", default="night"),
            'USER': config("MYSQL_DB_USER", default="t"),
            'PASSWORD': config("MYSQL_DB_PASS", default="uJdGq"),
            'HOST': config("MYSQL_DB_HOST", default="mysql"),
            'PORT': config("MYSQL_DB_PORT", default="33"),
            'OPTIONS': {'connect_timeout': 10},  # Added connection timeout
        },
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fa'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_ROOT = BASE_DIR / 'uploads'
MEDIA_URL = '/medias/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# user manager config
AUTH_USER_MODEL = 'accounts_module.User'

# sms module
FARAZ_SMS_API_KEY = config("FARAZ_SMS_API_KEY", default="dlBeLtlTn")

# rest framework settings
if DEBUG:
    DEFAULT_AUTHENTICATION_CLASSES = [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
else:
    # In production, ensure that DEBUG is False and Django admin works as expected
    DEFAULT_AUTHENTICATION_CLASSES = [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "utils_module.renderers.CustomJSONRenderer",  # update 'your_app' to your proper app name
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': DEFAULT_AUTHENTICATION_CLASSES,
    'EXCEPTION_HANDLER': 'utils_module.utils.custom_exception_handler',  # <-- Add here
}

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=31),
#     'ROTATE_REFRESH_TOKENS': False,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'VERIFYING_KEY': None,
#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',
#     'JTI_CLAIM': 'jti',
# }

# CORS configuration
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="http://localhost:3000", cast=Csv())

# print("CORS_ALLOWED_ORIGINS:", CORS_ALLOWED_ORIGINS)

CORS_ALLOW_CREDENTIALS = True
