# Generated by Django 4.2.20 on 2025-04-05 18:04

import accounts_module.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='موبایل')),
                ('introduction_url', models.URLField(blank=True, max_length=300, verbose_name='لینک معرفی')),
                ('first_name', models.CharField(blank=True, default='نام', max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, default='نام خانوادگی', max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('id_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='ابرکاربر')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده/تأیید نشده')),
                ('user_type', models.CharField(blank=True, choices=[('seller', 'Seller'), ('customer', 'Customer'), ('admin', 'admin')], default='customer', max_length=10, null=True, verbose_name='نوع کاربر')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserMediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('avatar', 'آواتار')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=accounts_module.models.user_media_files_upload_path, verbose_name='فایل')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='کپشن فایل')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فایل مربوط به کاربر',
                'verbose_name_plural': 'فایلهای مربوط به کاربران',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatar', to='accounts_module.usermediafiles', verbose_name='آواتار کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='introducer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_users', to=settings.AUTH_USER_MODEL, verbose_name='معرف'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
