# Generated by Django 4.2.20 on 2025-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediafiles',
            name='media_type',
            field=models.CharField(choices=[('avatar', 'آواتار')], default='avatar', max_length=20),
        ),
    ]
