# Generated by Django 4.2.20 on 2025-04-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0002_alter_usermediafiles_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermediafiles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='تأیید/مردود'),
        ),
    ]
