# Generated by Django 4.2.20 on 2025-04-06 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0003_usermediafiles_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediafiles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
