# Generated by Django 4.2.20 on 2025-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0004_alter_usermediafiles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediafiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
