# Generated by Django 4.2.20 on 2025-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0005_alter_usermediafiles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='کاربر', max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='نامشخص', max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
