# Generated by Django 4.2.20 on 2025-04-08 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0008_alter_usermediafiles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermediafiles',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='تصویر پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='usermediafiles',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_media_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
