# Generated by Django 4.2.20 on 2025-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0009_usermediafiles_is_global_alter_usermediafiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermediafiles',
            name='optimized',
            field=models.BooleanField(default=False),
        ),
    ]
