# Generated by Django 4.2.20 on 2025-04-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0010_usermediafiles_optimized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatars', to='accounts_module.usermediafiles', verbose_name='آواتار کاربر'),
        ),
    ]
