# Generated by Django 4.2.20 on 2025-04-05 18:04

from django.db import migrations, models
import django.db.models.deletion
import media_collection_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCollectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی مجموعه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته بندی مجموعه',
                'verbose_name_plural': 'دسته بندی های مجموعه',
            },
        ),
        migrations.CreateModel(
            name='ImageCollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to=media_collection_module.models.get_collection_image_upload_path, verbose_name='تصویر مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media_collection_module.imagecollectioncategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'تصویر مجموعه',
                'verbose_name_plural': 'تصاویر مجموعه',
            },
        ),
    ]
