# Generated by Django 4.2.20 on 2025-04-07 21:13

from django.db import migrations, models
import media_collection_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_collection_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollectionimage',
            name='image',
            field=models.ImageField(upload_to=media_collection_module.models.get_collection_image_upload_path, verbose_name='تصویر'),
        ),
    ]
