# Generated by Django 4.2.20 on 2025-04-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop_module.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='کافه/فروشگاه بی نام', max_length=100, verbose_name='نام فروشگاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('shop_url', models.URLField(blank=True, null=True, verbose_name='url کافه/فروشگاه')),
                ('shop_qr_code', models.ImageField(blank=True, null=True, upload_to=shop_module.models.shop_qr_code_upload_path, verbose_name='کد QR')),
                ('number_of_tables', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد میزهای کافه')),
                ('shop_type', models.CharField(choices=[('cafe', 'کافه'), ('shop', 'فروشگاه'), ('both', 'هردو')], max_length=10, verbose_name='نوع کافه/فروشگاه')),
                ('monetary_unit', models.CharField(choices=[('h_toman', 'هزار تومان'), ('toman', 'تومان')], default='toman', max_length=10, verbose_name='واحد قیمت ها')),
                ('id_card_upload', models.BooleanField(default=False, verbose_name='وضعیت بارگذاری کارت ملی')),
                ('certificate_upload', models.BooleanField(default=False, verbose_name='وضعیت بارگذاری مجوز')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید/مردود')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='ارسال رایگان')),
                ('pickup', models.BooleanField(default=False, verbose_name='ارسال با فی کافی')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='تلفن کافه/فروشگاه')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': 'کافه/فروشگاه',
                'verbose_name_plural': 'کافه ها/فروشگاه ها',
            },
        ),
        migrations.CreateModel(
            name='ShopOpenDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنجشنبه'), ('friday', 'جمعه')], max_length=20, verbose_name='روزهای کاری')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_days', to='shop_module.shop')),
            ],
            options={
                'verbose_name': 'روز کاری',
                'verbose_name_plural': 'روزهای کاری',
            },
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='طول جغرافیایی')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('country', models.CharField(blank=True, default='ایران', max_length=20, verbose_name='کشور')),
                ('is_complete', models.BooleanField(default=False, verbose_name='تکمیل/ناقص')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید/مردود')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کافه/فروشگاه',
                'verbose_name_plural': 'پروفایل کافه ها/فروشگاه ها',
            },
        ),
        migrations.CreateModel(
            name='ShopOpenHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(verbose_name='ساعت شروع')),
                ('close_time', models.TimeField(verbose_name='ساعت پایان')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_hours', to='shop_module.shopopendays')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
            },
        ),
        migrations.CreateModel(
            name='ShopMediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('logo', 'لوگو'), ('bannerimage', 'تصویر بنر'), ('bannervideo', 'ویدیو بنر'), ('certificate', 'مجوز'), ('idcard', 'کارت ملی')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=shop_module.models.shop_media_files_upload_path, verbose_name='فایل')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='کپشن فایل')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_media_files', to='shop_module.shop')),
            ],
            options={
                'verbose_name': 'فایل مربوط به کافه/فروشگاه',
                'verbose_name_plural': 'فایلهای مربوط به کافه/فروشگاه',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='banner',
            field=models.ManyToManyField(blank=True, related_name='shop_banner', to='shop_module.shopmediafiles', verbose_name='بنر کافه'),
        ),
        migrations.AddField(
            model_name='shop',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='shop_certificates', to='shop_module.shopmediafiles', verbose_name='مجوزهای کافه/فروشگاه'),
        ),
        migrations.AddField(
            model_name='shop',
            name='id_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_owner_id_card', to='shop_module.shopmediafiles', verbose_name='کارت ملی مالک'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_logo', to='shop_module.shopmediafiles', verbose_name='لوگو کافه/فروشگاه'),
        ),
        migrations.AddField(
            model_name='shop',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shop_module.shopprofile'),
        ),
        migrations.CreateModel(
            name='CafeTableQrCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_qr_code', models.ImageField(blank=True, null=True, upload_to=shop_module.models.shop_qr_code_upload_path, verbose_name='کد میزهای کافه QR')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_table_qr_codes', to='shop_module.shop')),
            ],
            options={
                'verbose_name': 'qr کد میز کافه',
                'verbose_name_plural': 'qr کدهای میزهای کافه',
            },
        ),
    ]
