# Generated by Django 4.2.20 on 2025-04-07 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0002_shopmediafiles_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmediafiles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
