# Generated by Django 4.2.20 on 2025-04-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0004_alter_shopmediafiles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmediafiles',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='تصویر پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='shopmediafiles',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_media_files', to='shop_module.shop'),
        ),
    ]
