# Generated by Django 4.2.20 on 2025-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0005_shopmediafiles_is_global_alter_shopmediafiles_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='manager_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل مدیر داخلی'),
        ),
        migrations.AddField(
            model_name='shop',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدیر داخلی'),
        ),
    ]
