# Generated by Django 4.2.20 on 2025-04-11 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_module', '0006_shop_manager_mobile_shop_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
