# Generated by Django 4.2.20 on 2025-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0008_shopmediafiles_optimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sell_in_marketplace',
            field=models.BooleanField(default=False, verbose_name='فروش در مارکت پلیس'),
        ),
        migrations.AddField(
            model_name='shop',
            name='show_in_marketplace',
            field=models.BooleanField(default=False, verbose_name='نمایش در مارکت پلیس'),
        ),
    ]
