# Generated by Django 4.2.20 on 2025-04-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0009_shop_sell_in_marketplace_shop_show_in_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
