# Generated by Django 4.2.20 on 2025-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0010_alter_shopprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
