# Generated by Django 4.2.20 on 2025-04-05 18:46

import article_module.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('article', 'تصویر مقاله')], default='article', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=article_module.models.article_media_files_upload_path, verbose_name='فایل')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='کپشن فایل')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_media_files', to='article_module.article')),
            ],
            options={
                'verbose_name': 'فایل مربوط به مقاله',
                'verbose_name_plural': 'فایلهای مربوط به مقالات',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_image', to='article_module.articlemediafiles', verbose_name='تصویر مقاله'),
        ),
    ]
