# Generated by Django 4.2.20 on 2025-04-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_articlemediafiles_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemediafiles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='تأیید/مردود'),
        ),
    ]
