# Generated by Django 4.2.20 on 2025-04-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_articlemediafiles_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemediafiles',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_media_files', to='article_module.article'),
        ),
    ]
