# Generated by Django 4.2.20 on 2025-04-06 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_module', '0004_alter_articlemediafiles_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemediafiles',
            name='article',
        ),
        migrations.AddField(
            model_name='articlemediafiles',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_media_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
