# Generated by Django 4.2.20 on 2025-04-07 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_remove_articlemediafiles_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemediafiles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
