# Generated by Django 4.2.20 on 2025-04-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_alter_articlemediafiles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemediafiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
