# Generated by Django 4.2.20 on 2025-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_alter_articlemediafiles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemediafiles',
            name='optimized',
            field=models.BooleanField(default=False),
        ),
    ]
