# Generated by Django 4.2.20 on 2025-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopMarketBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان بنر فروشگاه ها')),
                ('image', models.ImageField(upload_to='marketplace/shops/banners', verbose_name='تصویر بنر فروشگاه ها')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'بنر فروشگاه ها',
                'verbose_name_plural': 'بنرهای فروشگاه ها',
            },
        ),
    ]
